ActivateHttpFloodProtectionParam      = "yes"
ActivateScannersProbesProtectionParam = "yes"
ENDPOINT                              = "ALB"
ScannersProbesProtectionActivated     = "yes"
ReputationListsProtectionActivated    = "yes"
dev_alb_arn                           = "arn:aws:elasticloadbalancing:eu-west-1:1234:loadbalancer/app/Test-WAF/HASH"
