ActivateHttpFloodProtectionParam      = "yes"
ActivateScannersProbesProtectionParam = "yes"
ENDPOINT                              = "ALB"
ScannersProbesProtectionActivated     = "yes"
ReputationListsProtectionActivated    = "yes"
dev_alb_arn                           = "arn:aws:elasticloadbalancing:eu-west-2:1234:loadbalancer/app/k8s-game2048-ingress2-df2e96d3c6/5ef3ba1c838afcf0"
